<?php
/** @var $block Yireo\ExampleJsComponent2\Block\Example */
?>
<div style="border: 1px solid #00A5E3; background-color: #efefef; padding: 10px;">
    <div id="example2-output">This should be replaced with some example</div>
</div>

<script type="text/x-magento-init">
    {
        "#example2-output": {
            "example2":{"text":"<?php echo $block->getMessage(); ?>"}
        }
    }

</script>